--shows the all dataset
USE ETRADE
SELECT *
FROM [CUSTOMERS ]
--adds new customer information into the dataset
INSERT INTO [CUSTOMERS ]
(CUSTOMERNAME,CITY,BIRTHDATE,DISTRICT,GENDER)
VALUES ('MEHMET OZAL','ANTALYA','1992-12-03','ALANYA','E') 
--updates the given columns of dataset
--UPDATE [CUSTOMERS ] 
SET NATION ='TR',AGE=DATEDIFF(YEAR,BIRTHDATE,GETDATE())
--DELETE FROM CUSTOMERS (deletes all the table)
--TRUNCATE TABLE CUSTOMERS (deletes all the table bu)

UPDATE [CUSTOMERS ] SET GENDER='ERKEK' WHERE GENDER='E'
UPDATE [CUSTOMERS ] SET GENDER='KADIN' WHERE GENDER='K'
DELETE FROM [CUSTOMERS ] WHERE ID= 6
--devam et...
